### PR TITLE
Duplicate prevention for one time charges

### PR DESCRIPTION
**Pull request by jacegu**
This was missing in the original PR that added duplicate prevention support.

### CODE REVIEW

**Comment by jacegu** [comment]
Poor man's Travis CI: Both unit and remote specs pass.

**Comment by jacegu** [comment]
I have manually tested this against our app and works as expected. Merging...

**Comment by npverni** [comment]
Could you open this PR against the official chargify repo?

**Comment by jacegu** [comment]
@npverni sure. On it.

**Comment by jacegu** [comment]
@npverni Opened here: https://github.com/chargify/chargify_api_ares/pull/111

**Pull request merged**
